<!DOCTYPE html>



  


<html class="theme-next gemini use-motion" lang="zh-Hans">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
















  
  
    
  
  <link href="//cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.min.css" rel="stylesheet" type="text/css" />







  

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=5.1.4" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.4">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.4">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.4" color="#222">





  <meta name="keywords" content="Hexo, NexT" />










<meta name="description" content="目录  异常处理  -异常传播  -协程异常处理器  -取消和异常  -异常聚合  -监管-[监管] job(#监管) -[监管作用域](#监管作用域) -[监管协程中的异常](#监管协程中的异常)   异常处理本节介绍异常处理和异常的取消。我们已经知道，取消的协程会在挂起点上引发 CancellationException，并且协程机制会忽略它。但是，如果在取消过程中引发异常或同一个协程的多个子">
<meta property="og:type" content="website">
<meta property="og:title" content="LeBron_Six 的博客">
<meta property="og:url" content="http://smuyyh.top/kotlin-in-chinese/coroutines/ExceptionHandling.html">
<meta property="og:site_name" content="LeBron_Six 的博客">
<meta property="og:description" content="目录  异常处理  -异常传播  -协程异常处理器  -取消和异常  -异常聚合  -监管-[监管] job(#监管) -[监管作用域](#监管作用域) -[监管协程中的异常](#监管协程中的异常)   异常处理本节介绍异常处理和异常的取消。我们已经知道，取消的协程会在挂起点上引发 CancellationException，并且协程机制会忽略它。但是，如果在取消过程中引发异常或同一个协程的多个子">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2022-10-12T02:57:26.189Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="LeBron_Six 的博客">
<meta name="twitter:description" content="目录  异常处理  -异常传播  -协程异常处理器  -取消和异常  -异常聚合  -监管-[监管] job(#监管) -[监管作用域](#监管作用域) -[监管协程中的异常](#监管协程中的异常)   异常处理本节介绍异常处理和异常的取消。我们已经知道，取消的协程会在挂起点上引发 CancellationException，并且协程机制会忽略它。但是，如果在取消过程中引发异常或同一个协程的多个子">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Gemini',
    version: '5.1.4',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="http://smuyyh.top/kotlin-in-chinese/coroutines/ExceptionHandling.html"/>





  <title> | LeBron_Six 的博客</title>
  








</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/"  class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">LeBron_Six 的博客</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle"></p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-categories">
          <a href="/categories/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-th"></i> <br />
            
            分类
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />
            
            归档
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user"></i> <br />
            
            关于
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    
    
    
    <div class="post-block page">
      <header class="post-header">

	<h1 class="post-title" itemprop="name headline"></h1>



</header>

      
      
      
      <div class="post-body">
        
        
          <p>目录</p>
<ul>
<li><a href="#异常处理">异常处理</a><br>  -<a href="#异常传播">异常传播</a><br>  -<a href="#协程异常处理器">协程异常处理器</a><br>  -<a href="#取消和异常">取消和异常</a><br>  -<a href="#异常聚合">异常聚合</a><br>  -<a href="#监管">监管</a><pre><code>-[监管] job(#监管)
-[监管作用域](#监管作用域)
-[监管协程中的异常](#监管协程中的异常)
</code></pre></li>
</ul>
<h2 id="异常处理"><a href="#异常处理" class="headerlink" title="异常处理"></a>异常处理</h2><p>本节介绍异常处理和异常的取消。我们已经知道，取消的协程会在挂起点上引发 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-cancellation-exception/index.html" target="_blank" rel="external">CancellationException</a>，并且协程机制会忽略它。但是，如果在取消过程中引发异常或同一个协程的多个子协程发异常，会发生什么呢？</p>
<h3 id="异常传播"><a href="#异常传播" class="headerlink" title="异常传播"></a>异常传播</h3><p>协程构建器有两种形式：自动传播异常（<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html" target="_blank" rel="external">launch</a>和<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html" target="_blank" rel="external">actor</a>）或向用户暴露异常（<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html" target="_blank" rel="external">async</a>和<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/produce.html" target="_blank" rel="external">produce</a>）。前者将异常视为未处理的异常，类似于Java的Thread.uncaughtExceptionHandler，而后者则依靠用户使用最终异常，例如通过 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/await.html" target="_blank" rel="external">await</a> 或 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/receive.html" target="_blank" rel="external">receive</a>（produce和receive将在Channels部分中介绍）。</p>
<p>可以借助GlobalScope中创建协程的简单示例来演示：</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">import</span> kotlinx.coroutines.*</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</div><div class="line">    <span class="keyword">val</span> job = GlobalScope.launch &#123;</div><div class="line">        println(<span class="string">"Throwing exception from launch"</span>)</div><div class="line">        <span class="keyword">throw</span> IndexOutOfBoundsException() <span class="comment">// Will be printed to the console by Thread.defaultUncaughtExceptionHandler</span></div><div class="line">    &#125;</div><div class="line">    job.join()</div><div class="line">    println(<span class="string">"Joined failed job"</span>)</div><div class="line">    <span class="keyword">val</span> deferred = GlobalScope.async &#123;</div><div class="line">        println(<span class="string">"Throwing exception from async"</span>)</div><div class="line">        <span class="keyword">throw</span> ArithmeticException() <span class="comment">// Nothing is printed, relying on user to call await</span></div><div class="line">    &#125;</div><div class="line">    <span class="keyword">try</span> &#123;</div><div class="line">        deferred.await()</div><div class="line">        println(<span class="string">"Unreached"</span>)</div><div class="line">    &#125; <span class="keyword">catch</span> (e: ArithmeticException) &#123;</div><div class="line">        println(<span class="string">"Caught ArithmeticException"</span>)</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>这段代码的输出如下(附带调试信息)：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line">Throwing exception from launch</div><div class="line">Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" java.lang.IndexOutOfBoundsException</div><div class="line">Joined failed job</div><div class="line">Throwing exception from async</div><div class="line">Caught ArithmeticException</div></pre></td></tr></table></figure>
<h3 id="协程异常处理器"><a href="#协程异常处理器" class="headerlink" title="协程异常处理器"></a>协程异常处理器</h3><p>但是，如果不想将所有异常打印到控制台怎么办？ <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-exception-handler/index.html" target="_blank" rel="external">CoroutineExceptionHandler</a> 上下文元素可以视为协程的通用 <code>catch</code> 块，在协程中可能发生自定义日志记录或异常处理。它类似于使用Thread.uncaughtExceptionHandler。</p>
<p>在JVM上，可以通过ServiceLoader注册CoroutineExceptionHandler来为所有协程重新定义全局异常处理程序。全局异常处理程序与Thread.defaultUncaughtExceptionHandler相似，在没有其他特定的处理程序注册时使用。在Android上，uncaughtExceptionPreHandler被安装为全局协程异常处理程序。</p>
<p>仅在用户未处理的异常上会调用CoroutineExceptionHandler，因此在<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html" target="_blank" rel="external">async</a>生成器等中注册它无效。</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">val</span> handler = CoroutineExceptionHandler &#123; _, exception -&gt; </div><div class="line">    println(<span class="string">"Caught <span class="variable">$exception</span>"</span>) </div><div class="line">&#125;</div><div class="line"><span class="keyword">val</span> job = GlobalScope.launch(handler) &#123;</div><div class="line">    <span class="keyword">throw</span> AssertionError()</div><div class="line">&#125;</div><div class="line"><span class="keyword">val</span> deferred = GlobalScope.async(handler) &#123;</div><div class="line">    <span class="keyword">throw</span> ArithmeticException() <span class="comment">// Nothing will be printed, relying on user to call deferred.await()</span></div><div class="line">&#125;</div><div class="line">joinAll(job, deferred)</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">Caught java.lang.AssertionError</div></pre></td></tr></table></figure>
<h3 id="取消和异常"><a href="#取消和异常" class="headerlink" title="取消和异常"></a>取消和异常</h3><p>取消与异常紧密相关。协程在内部使用CancellationException进行取消，所有处理程序都将忽略这些异常，因此它们仅应用作其他调试信息的源，可以通过catch块获取这些信息。使用 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/cancel.html" target="_blank" rel="external">Job.cancel</a> 取消协程时，协程终止，但不取消其父级。</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">val</span> job = launch &#123;</div><div class="line">    <span class="keyword">val</span> child = launch &#123;</div><div class="line">        <span class="keyword">try</span> &#123;</div><div class="line">            delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">        &#125; <span class="keyword">finally</span> &#123;</div><div class="line">            println(<span class="string">"Child is cancelled"</span>)</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">    yield()</div><div class="line">    println(<span class="string">"Cancelling child"</span>)</div><div class="line">    child.cancel()</div><div class="line">    child.join()</div><div class="line">    yield()</div><div class="line">    println(<span class="string">"Parent is not cancelled"</span>)</div><div class="line">&#125;</div><div class="line">job.join()</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">Cancelling child</div><div class="line">Child is cancelled</div><div class="line">Parent is not cancelled</div></pre></td></tr></table></figure>
<p>如果协程遇到除CancellationException以外的其他异常，它将取消具有该异常的父对象。此行为不能被覆盖，并且用于为不依赖于CoroutineExceptionHandler实现的结构化并发提供稳定的协程层次结构。当父级的所有子级终止时，父级将处理原始异常。</p>
<p>这也是为什么在这些示例中，CoroutineExceptionHandler始终注册到在GlobalScope中创建的协程的原因。将异常处理程序注册到在主runBlocking范围内启动的协程中没有意义，因为尽管安装了该处理程序，但当其子级异常完成时，主协程将始终被取消。</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">val</span> handler = CoroutineExceptionHandler &#123; _, exception -&gt; </div><div class="line">    println(<span class="string">"Caught <span class="variable">$exception</span>"</span>) </div><div class="line">&#125;</div><div class="line"><span class="keyword">val</span> job = GlobalScope.launch(handler) &#123;</div><div class="line">    launch &#123; <span class="comment">// the first child</span></div><div class="line">        <span class="keyword">try</span> &#123;</div><div class="line">            delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">        &#125; <span class="keyword">finally</span> &#123;</div><div class="line">            withContext(NonCancellable) &#123;</div><div class="line">                println(<span class="string">"Children are cancelled, but exception is not handled until all children terminate"</span>)</div><div class="line">                delay(<span class="number">100</span>)</div><div class="line">                println(<span class="string">"The first child finished its non cancellable block"</span>)</div><div class="line">            &#125;</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">    launch &#123; <span class="comment">// the second child</span></div><div class="line">        delay(<span class="number">10</span>)</div><div class="line">        println(<span class="string">"Second child throws an exception"</span>)</div><div class="line">        <span class="keyword">throw</span> ArithmeticException()</div><div class="line">    &#125;</div><div class="line">&#125;</div><div class="line">job.join()</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">Second child throws an exception</div><div class="line">Children are cancelled, but exception is not handled until all children terminate</div><div class="line">The first child finished its non cancellable block</div><div class="line">Caught java.lang.ArithmeticException</div></pre></td></tr></table></figure>
<h3 id="异常聚合"><a href="#异常聚合" class="headerlink" title="异常聚合"></a>异常聚合</h3><p>如果协程的多个子级抛出异常会怎样？一般规则是“第一个异常获胜”，因此第一个引发的异常向处理器暴露。但这可能导致丢失的异常，例如，协程在其 <code>finally</code> 块中抛出异常。因此，抑制了其他异常。</p>
<p>解决方案之一是分别报告每个异常，但是Deferred.await应该具有相同的机制来避免行为不一致，这将导致协程的实现细节（无论它是否将工作的一部分委派给了孩子或不）泄漏到其异常处理程序。</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">import</span> kotlinx.coroutines.*</div><div class="line"><span class="keyword">import</span> java.io.*</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</div><div class="line">    <span class="keyword">val</span> handler = CoroutineExceptionHandler &#123; _, exception -&gt;</div><div class="line">        println(<span class="string">"Caught <span class="variable">$exception</span> with suppressed <span class="subst">$&#123;exception.suppressed.contentToString()&#125;</span>"</span>)</div><div class="line">    &#125;</div><div class="line">    <span class="keyword">val</span> job = GlobalScope.launch(handler) &#123;</div><div class="line">        launch &#123;</div><div class="line">            <span class="keyword">try</span> &#123;</div><div class="line">                delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">            &#125; <span class="keyword">finally</span> &#123;</div><div class="line">                <span class="keyword">throw</span> ArithmeticException()</div><div class="line">            &#125;</div><div class="line">        &#125;</div><div class="line">        launch &#123;</div><div class="line">            delay(<span class="number">100</span>)</div><div class="line">            <span class="keyword">throw</span> IOException()</div><div class="line">        &#125;</div><div class="line">        delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">    &#125;</div><div class="line">    job.join()  </div><div class="line">&#125;</div></pre></td></tr></table></figure>
<blockquote>
<p>注意：以上代码仅在支持抑制异常的JDK7 +上才能正常工作</p>
</blockquote>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">Caught java.io.IOException with suppressed [java.lang.ArithmeticException]</div></pre></td></tr></table></figure>
<blockquote>
<p>请注意，该机制当前仅在Java版本1.7+上有效。 JS和Native的限制是暂时的，将来会修复。</p>
</blockquote>
<p>取消异常是透明的，默认情况下是未包装的：</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">val</span> handler = CoroutineExceptionHandler &#123; _, exception -&gt;</div><div class="line">    println(<span class="string">"Caught original <span class="variable">$exception</span>"</span>)</div><div class="line">&#125;</div><div class="line"><span class="keyword">val</span> job = GlobalScope.launch(handler) &#123;</div><div class="line">    <span class="keyword">val</span> inner = launch &#123;</div><div class="line">        launch &#123;</div><div class="line">            launch &#123;</div><div class="line">                <span class="keyword">throw</span> IOException()</div><div class="line">            &#125;</div><div class="line">        &#125;</div><div class="line">    &#125;</div><div class="line">    <span class="keyword">try</span> &#123;</div><div class="line">        inner.join()</div><div class="line">    &#125; <span class="keyword">catch</span> (e: CancellationException) &#123;</div><div class="line">        println(<span class="string">"Rethrowing CancellationException with original cause"</span>)</div><div class="line">        <span class="keyword">throw</span> e</div><div class="line">    &#125;</div><div class="line">&#125;</div><div class="line">job.join()</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">Rethrowing CancellationException with original cause</div><div class="line">Caught original java.io.IOException</div></pre></td></tr></table></figure>
<h3 id="监管"><a href="#监管" class="headerlink" title="监管"></a>监管</h3><p>正如我们之前研究的那样，取消是在整个协程层次中传播的双向关系。但是，如果需要单向取消怎么办？</p>
<p>此类需求的一个很好的例子是在其范围内定义了工作的UI组件。如果UI的任何子任务失败，则不必总是取消（有效地杀死）整个UI组件，但是如果UI组件被破坏（并且其工作被取消），则必须使所有子任务失败，因为他们的结果不再需要。</p>
<p>另一个示例是一个服务器进程，该进程产生多个子作业，并且需要监督它们的执行，跟踪其失败并仅重新启动那些失败的子作业。</p>
<h3 id="监管-job"><a href="#监管-job" class="headerlink" title="监管 job"></a>监管 job</h3><p>为此，可以使用<a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-supervisor-job.html" target="_blank" rel="external">SupervisorJob</a>。 它与常规Job相似，唯一的不同是取消仅向下传播。 举一个例子：</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div><div class="line">25</div><div class="line">26</div><div class="line">27</div><div class="line">28</div><div class="line">29</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">import</span> kotlinx.coroutines.*</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</div><div class="line">    <span class="keyword">val</span> supervisor = SupervisorJob()</div><div class="line">    with(CoroutineScope(coroutineContext + supervisor)) &#123;</div><div class="line">        <span class="comment">// launch the first child -- its exception is ignored for this example (don't do this in practice!)</span></div><div class="line">        <span class="keyword">val</span> firstChild = launch(CoroutineExceptionHandler &#123; _, _ -&gt;  &#125;) &#123;</div><div class="line">            println(<span class="string">"First child is failing"</span>)</div><div class="line">            <span class="keyword">throw</span> AssertionError(<span class="string">"First child is cancelled"</span>)</div><div class="line">        &#125;</div><div class="line">        <span class="comment">// launch the second child</span></div><div class="line">        <span class="keyword">val</span> secondChild = launch &#123;</div><div class="line">            firstChild.join()</div><div class="line">            <span class="comment">// Cancellation of the first child is not propagated to the second child</span></div><div class="line">            println(<span class="string">"First child is cancelled: <span class="subst">$&#123;firstChild.isCancelled&#125;</span>, but second one is still active"</span>)</div><div class="line">            <span class="keyword">try</span> &#123;</div><div class="line">                delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">            &#125; <span class="keyword">finally</span> &#123;</div><div class="line">                <span class="comment">// But cancellation of the supervisor is propagated</span></div><div class="line">                println(<span class="string">"Second child is cancelled because supervisor is cancelled"</span>)</div><div class="line">            &#125;</div><div class="line">        &#125;</div><div class="line">        <span class="comment">// wait until the first child fails &amp; completes</span></div><div class="line">        firstChild.join()</div><div class="line">        println(<span class="string">"Cancelling supervisor"</span>)</div><div class="line">        supervisor.cancel()</div><div class="line">        secondChild.join()</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">First child is failing</div><div class="line">First child is cancelled: true, but second one is still active</div><div class="line">Cancelling supervisor</div><div class="line">Second child is cancelled because supervisor is cancelled</div></pre></td></tr></table></figure>
<h3 id="监管作用域"><a href="#监管作用域" class="headerlink" title="监管作用域"></a>监管作用域</h3><p>对于有作用域的并发，出于相同的目的，可以使用 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/supervisor-scope.html" target="_blank" rel="external">supervisorScope</a> 代替 <a href="https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html" target="_blank" rel="external">coroutineScope</a>。它仅在一个方向上传播取消，并且仅在失败后才取消所有子级。它也像coroutineScope一样等待所有孩子完成任务。</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">import</span> kotlin.coroutines.*</div><div class="line"><span class="keyword">import</span> kotlinx.coroutines.*</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</div><div class="line">    <span class="keyword">try</span> &#123;</div><div class="line">        supervisorScope &#123;</div><div class="line">            <span class="keyword">val</span> child = launch &#123;</div><div class="line">                <span class="keyword">try</span> &#123;</div><div class="line">                    println(<span class="string">"Child is sleeping"</span>)</div><div class="line">                    delay(<span class="built_in">Long</span>.MAX_VALUE)</div><div class="line">                &#125; <span class="keyword">finally</span> &#123;</div><div class="line">                    println(<span class="string">"Child is cancelled"</span>)</div><div class="line">                &#125;</div><div class="line">            &#125;</div><div class="line">            <span class="comment">// Give our child a chance to execute and print using yield </span></div><div class="line">            yield()</div><div class="line">            println(<span class="string">"Throwing exception from scope"</span>)</div><div class="line">            <span class="keyword">throw</span> AssertionError()</div><div class="line">        &#125;</div><div class="line">    &#125; <span class="keyword">catch</span>(e: AssertionError) &#123;</div><div class="line">        println(<span class="string">"Caught assertion error"</span>)</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">Child is sleeping</div><div class="line">Throwing exception from scope</div><div class="line">Child is cancelled</div><div class="line">Caught assertion error</div></pre></td></tr></table></figure>
<h3 id="监管协程中的异常"><a href="#监管协程中的异常" class="headerlink" title="监管协程中的异常"></a>监管协程中的异常</h3><p>常规job和监管job之间的另一个关键区别是异常处理。每个子job都应通过异常处理机制自行处理其异常。这种差异来自于子job的失败不会传播给父job.</p>
<figure class="highlight kotlin"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">import</span> kotlin.coroutines.*</div><div class="line"><span class="keyword">import</span> kotlinx.coroutines.*</div><div class="line"></div><div class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</div><div class="line">    <span class="keyword">val</span> handler = CoroutineExceptionHandler &#123; _, exception -&gt; </div><div class="line">        println(<span class="string">"Caught <span class="variable">$exception</span>"</span>) </div><div class="line">    &#125;</div><div class="line">    supervisorScope &#123;</div><div class="line">        <span class="keyword">val</span> child = launch(handler) &#123;</div><div class="line">            println(<span class="string">"Child throws an exception"</span>)</div><div class="line">            <span class="keyword">throw</span> AssertionError()</div><div class="line">        &#125;</div><div class="line">        println(<span class="string">"Scope is completing"</span>)</div><div class="line">    &#125;</div><div class="line">    println(<span class="string">"Scope is completed"</span>)</div><div class="line">&#125;</div></pre></td></tr></table></figure>
<p>此代码的输出是：</p>
<figure class="highlight shell"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">Scope is completing</div><div class="line">Child throws an exception</div><div class="line">Caught java.lang.AssertionError</div><div class="line">Scope is completed</div></pre></td></tr></table></figure>
        
      </div>
      
      
      
    </div>
    
    
    
  </div>


          </div>
          


          

  
    <div class="comments" id="comments">
      
        <div id="gitment-container"></div>
      
    </div>

  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <img class="site-author-image" itemprop="image"
                src="https://avatars0.githubusercontent.com/u/15133565?s=460&v=4"
                alt="LeBron_Six" />
            
              <p class="site-author-name" itemprop="name">LeBron_Six</p>
              <p class="site-description motion-element" itemprop="description">欢迎访问我的博客~</p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives/">
              
                  <span class="site-state-item-count">28</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-categories">
                <a href="/categories/index.html">
                  <span class="site-state-item-count">3</span>
                  <span class="site-state-item-name">分类</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-tags">
                <a href="/tags/index.html">
                  <span class="site-state-item-count">35</span>
                  <span class="site-state-item-name">标签</span>
                </a>
              </div>
            

          </nav>

          

          
            <div class="links-of-author motion-element">
                
                  <span class="links-of-author-item">
                    <a href="https://github.com/smuyyh" target="_blank" title="GitHub">
                      
                        <i class="fa fa-fw fa-github"></i>GitHub</a>
                  </span>
                
                  <span class="links-of-author-item">
                    <a href="mailto:smuyyh@gmail.com" target="_blank" title="E-Mail">
                      
                        <i class="fa fa-fw fa-envelope"></i>E-Mail</a>
                  </span>
                
            </div>
          

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#异常处理"><span class="nav-number">1.</span> <span class="nav-text">异常处理</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#异常传播"><span class="nav-number">1.1.</span> <span class="nav-text">异常传播</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#协程异常处理器"><span class="nav-number">1.2.</span> <span class="nav-text">协程异常处理器</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#取消和异常"><span class="nav-number">1.3.</span> <span class="nav-text">取消和异常</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#异常聚合"><span class="nav-number">1.4.</span> <span class="nav-text">异常聚合</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#监管"><span class="nav-number">1.5.</span> <span class="nav-text">监管</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#监管-job"><span class="nav-number">1.6.</span> <span class="nav-text">监管 job</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#监管作用域"><span class="nav-number">1.7.</span> <span class="nav-text">监管作用域</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#监管协程中的异常"><span class="nav-number">1.8.</span> <span class="nav-text">监管协程中的异常</span></a></li></ol></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; 2016 &mdash; <span itemprop="copyrightYear">2022</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder"><a href="https://github.com/smuyyh" target="_blank">LeBron_Six</a></span>

  
</div>









        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
  

  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/fastclick/1.0.6/fastclick.min.js"></script>
  

  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.lazyload/1.9.3/jquery.lazyload.min.js"></script>
  

  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js"></script>
  

  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/velocity/1.2.3/velocity.ui.min.js"></script>
  

  
  
    <script type="text/javascript" src="//cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.pack.js"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.4"></script>



  
  


  <script type="text/javascript" src="/js/src/affix.js?v=5.1.4"></script>

  <script type="text/javascript" src="/js/src/schemes/pisces.js?v=5.1.4"></script>



  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.4"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.4"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.4"></script>



  


  




	





  





  







<!-- LOCAL: You can save these files to your site and update links -->
    
        
        <link rel="stylesheet" href="https://www.wenjunjiang.win/css/gitment.css">
        <script src="https://www.wenjunjiang.win/js/gitment.js"></script>
    
<!-- END LOCAL -->

    
      <style>
        a.gitment-editor-footer-tip { display: none; }
        .gitment-container.gitment-footer-container { display: none; }
      </style>
    

    
      <script type="text/javascript">
      function renderGitment(){
        var gitment = new Gitment({
            id: window.location.pathname, 
            owner: 'smuyyh',
            repo: 'smuyyh.github.io',
            
            oauth: {
            
            
                client_secret: '774c6e487b59087f22aea6b51bbbd69e2ef0a5c2',
            
                client_id: '0a452de0f03398d1ea74'
            }});
        gitment.render('gitment-container');
      }

      
      renderGitment();
      
      </script>
    







  





  

  

  

  
  

  

  

  

</body>
</html>
